#!/usr/bin/env python3
"""
Build RC4-related anomalous TLS handshake pcaps using Scapy's TLS layer.
Generates one pcap per rule so each can be verified independently:

  sid:1000011  TLS server negotiated RC4 cipher suite
               -> tls_sid1000011_server_negotiated_rc4.pcap
  sid:1000012  TLS client cipher suites list is RC4-only
               -> tls_sid1000012_client_cipher_suites_rc4_only.pcap
  sid:1000013  TLS client proposed RC4 cipher suite
               -> tls_sid1000013_client_proposed_rc4.pcap

Dependencies:
    pip install scapy cryptography

Usage:
    python3 scapy_tls_rc4_per_rule.py
"""

from scapy.all import IP, TCP, wrpcap
from scapy.layers.tls.record import TLS
from scapy.layers.tls.handshake import TLSClientHello, TLSServerHello

CLIENT_IP, SERVER_IP = "192.168.56.101", "192.168.56.201"
SERVER_PORT = 443

# RC4-based cipher suite ids (subset of RFC 7465 Appendix A)
CIPHER_RC4_RSA_SHA        = 0x0005  # TLS_RSA_WITH_RC4_128_SHA
CIPHER_RC4_RSA_MD5        = 0x0004  # TLS_RSA_WITH_RC4_128_MD5
CIPHER_ECDHE_RC4_RSA      = 0xc011  # TLS_ECDHE_RSA_WITH_RC4_128_SHA

# Safe/modern cipher suites, mixed in with RC4 for realistic scenarios
CIPHER_ECDHE_RSA_AES_GCM   = 0xc02f  # TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
CIPHER_ECDHE_ECDSA_AES_GCM = 0xc02b  # TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

TLS12_VERSION = 0x0303  # RC4 suites don't exist in TLS 1.3, pin handshake to TLS 1.2


def build_session(src_port, client_ciphers, server_cipher, isn_c, isn_s):
    """Build a full TCP 3-way handshake + ClientHello/ServerHello session."""
    pkts = []

    pkts.append(IP(src=CLIENT_IP, dst=SERVER_IP) /
                TCP(sport=src_port, dport=SERVER_PORT, flags="S", seq=isn_c))
    pkts.append(IP(src=SERVER_IP, dst=CLIENT_IP) /
                TCP(sport=SERVER_PORT, dport=src_port, flags="SA", seq=isn_s, ack=isn_c + 1))
    pkts.append(IP(src=CLIENT_IP, dst=SERVER_IP) /
                TCP(sport=src_port, dport=SERVER_PORT, flags="A", seq=isn_c + 1, ack=isn_s + 1))

    client_hello = TLS(msg=[
        TLSClientHello(
            version=TLS12_VERSION,
            ciphers=client_ciphers,
        )
    ])
    ch_bytes = bytes(client_hello)
    pkts.append(IP(src=CLIENT_IP, dst=SERVER_IP) /
                TCP(sport=src_port, dport=SERVER_PORT, flags="PA",
                    seq=isn_c + 1, ack=isn_s + 1) /
                ch_bytes)

    pkts.append(IP(src=SERVER_IP, dst=CLIENT_IP) /
                TCP(sport=SERVER_PORT, dport=src_port, flags="A",
                    seq=isn_s + 1, ack=isn_c + 1 + len(ch_bytes)))

    server_hello = TLS(msg=[
        TLSServerHello(
            version=TLS12_VERSION,
            cipher=server_cipher,
        )
    ])
    sh_bytes = bytes(server_hello)
    pkts.append(IP(src=SERVER_IP, dst=CLIENT_IP) /
                TCP(sport=SERVER_PORT, dport=src_port, flags="PA",
                    seq=isn_s + 1, ack=isn_c + 1 + len(ch_bytes)) /
                sh_bytes)

    pkts.append(IP(src=CLIENT_IP, dst=SERVER_IP) /
                TCP(sport=src_port, dport=SERVER_PORT, flags="A",
                    seq=isn_c + 1 + len(ch_bytes), ack=isn_s + 1 + len(sh_bytes)))

    return pkts, ch_bytes, sh_bytes


def verify(name, ch_bytes, sh_bytes, expect_client_has_rc4, expect_server_is_rc4):
    """Re-parse the generated bytes and assert the RC4 conditions hold as intended."""
    ch_parsed = TLS(ch_bytes)
    sh_parsed = TLS(sh_bytes)
    client_ciphers = list(ch_parsed.msg[0].ciphers)
    server_cipher = sh_parsed.msg[0].cipher

    print(f"\n[{name}]")
    print("  client ciphers:", [hex(c) for c in client_ciphers])
    print("  server selected:", hex(server_cipher))

    rc4_set = {CIPHER_RC4_RSA_SHA, CIPHER_RC4_RSA_MD5, CIPHER_ECDHE_RC4_RSA}
    client_has_rc4 = any(c in rc4_set for c in client_ciphers)
    server_is_rc4 = server_cipher in rc4_set

    assert client_has_rc4 == expect_client_has_rc4, f"{name}: client RC4 state mismatch"
    assert server_is_rc4 == expect_server_is_rc4, f"{name}: server RC4 state mismatch"
    print("  OK verified")


# ---- sid:1000011  server selected RC4 ----
# Client proposes a normal mix (2 safe suites + 1 RC4 for legacy compatibility),
# but the server incorrectly selects the RC4 suite.
pkts_1000011, ch1, sh1 = build_session(
    src_port=51001,
    client_ciphers=[CIPHER_ECDHE_RSA_AES_GCM, CIPHER_ECDHE_ECDSA_AES_GCM, CIPHER_RC4_RSA_SHA],
    server_cipher=CIPHER_RC4_RSA_SHA,
    isn_c=1000, isn_s=5000,
)
wrpcap("tls_sid1000011_server_negotiated_rc4.pcap", pkts_1000011)
verify("sid:1000011 server_negotiated_rc4", ch1, sh1,
       expect_client_has_rc4=True, expect_server_is_rc4=True)


# ---- sid:1000012  client's cipher list is RC4-only ----
# Per RFC 7465 the server should abort the handshake here. To still exercise
# the ServerHello parsing path, the server responds by (non-compliantly)
# selecting one of the RC4 suites. This is expected to also trigger
# sid:1000011 on the same flow -- that overlap is intentional.
pkts_1000012, ch2, sh2 = build_session(
    src_port=51002,
    client_ciphers=[CIPHER_RC4_RSA_SHA, CIPHER_RC4_RSA_MD5],
    server_cipher=CIPHER_RC4_RSA_SHA,
    isn_c=2000, isn_s=6000,
)
wrpcap("tls_sid1000012_client_cipher_suites_rc4_only.pcap", pkts_1000012)
verify("sid:1000012 client_cipher_suites_rc4_only", ch2, sh2,
       expect_client_has_rc4=True, expect_server_is_rc4=True)


# ---- sid:1000013  client proposed RC4 among other options ----
# Server behaves correctly (selects a safe suite, never selects RC4).
# Only this rule should fire; sid:1000011 and sid:1000012 must NOT fire.
pkts_1000013, ch3, sh3 = build_session(
    src_port=51003,
    client_ciphers=[CIPHER_ECDHE_RSA_AES_GCM, CIPHER_ECDHE_ECDSA_AES_GCM, CIPHER_ECDHE_RC4_RSA],
    server_cipher=CIPHER_ECDHE_RSA_AES_GCM,
    isn_c=3000, isn_s=7000,
)
wrpcap("tls_sid1000013_client_proposed_rc4.pcap", pkts_1000013)
verify("sid:1000013 client_proposed_rc4", ch3, sh3,
       expect_client_has_rc4=True, expect_server_is_rc4=False)


print("\nDone. Generated 3 pcap files:")
print("  tls_sid1000011_server_negotiated_rc4.pcap")
print("  tls_sid1000012_client_cipher_suites_rc4_only.pcap")
print("  tls_sid1000013_client_proposed_rc4.pcap")